apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-hellotwo
spec:
  namespace: argocd
  replicas: 2
  selector:
    matchLabels:
      app: go-app-hellotwo
  template:
    metadata:
      labels:
        app: go-app-hellotwo
    spec:
      containers:
        - name: go-app-hellotwo
          image: ghcr.io/bf-luca/argo-ghcr-code-hellotwo:171c2b9d132c7357ab02c8ef8ece9a9aaec2fe1f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
