apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-helloserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app-helloserver
  template:
    metadata:
      labels:
        app: go-app-helloserver
    spec:
      containers:
        - name: go-app-helloserver
          image: bf-luca/argo-ghcr-code-helloserver:0d0141e038b5d80a4d2bb4486906e9bd88517ba3
          ports:
            - containerPort: 80
