apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-hellotwo
spec:
  namespace: argocd
  replicas: 2
  selector:
    matchLabels:
      app: go-app-hellotwo
  template:
    metadata:
      labels:
        app: go-app-hellotwo
    spec:
      containers:
        - name: go-app-hellotwo
          image: ghcr.io/bf-luca/argo-ghcr-code-hellotwo:9932505fbee85c7cec65b4c1acd45fc311410586
          imagePullPolicy: Always
          ports:
            - containerPort: 80
