apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: bf-luca/argo-ghcr-code:b8636df9d73bdf02c48857b6680bdcf125e75215
          imagePullPolicy: Always
          ports:
            - containerPort: 80
