apiVersion: v1
kind: Service
metadata:
  name: go-app-hellotwo
spec:
  namespace: argocd
  type: NodePort
  selector:
    app: go-app-hellotwo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31001
