apiVersion: v1
kind: Service
metadata:
  name: go-app-helloserver
spec:
  namespace: argocd
  type: NodePort
  selector:
    app: go-app-helloserver
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
